# Generated by Django 5.2.6 on 2025-11-07 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, default='static/img/avatar-perfil.jpg', null=True, upload_to=''),
        ),
    ]
